### ISSUE TITLE
Why can't compile?

### ISSUE THREAD

**Issue by longmalongma** [Saira05/DPRNet-#1]
Hello,think you for your work,but when I try to run your code in my computer,I can't compile,I met this problem.do you know why?can you send me your files have compiled,such as tf_conv3p.so
to my email,my email is that:1442342449@qq.com.
tensorflow/core/lib/gtl/array_slice_internal.h:230:7: note:   candidate expects 1 argument, 2 provided
g++: error: register_op.o: No such file or directory
g++: error: tf_conv3p.so_cuda.o: No such file or directory
g++: error: tf_conv3p.so_cpu.o: No such file or directory
rm: cannot remove 'tf_conv3p.so_cpu.o': No such file or directory
rm: cannot remove 'tf_conv3p.so_cuda.o': No such file or directory

**Comment by saira05** [comment]
This file need to be compiled on your own pc. Kindly tell me which version of tensorflow you are using.

**Comment by longmalongma** [comment]
> This file need to be compiled on your own pc. Kindly tell me which version of tensorflow you are using.

tensorflow-gpu                     1.9.0                    
RTX2080
CUDA 9.0

**Comment by saira05** [comment]
Are you compiling this file?
tf_conv3p_compile_tf14.sh

**Comment by saira05** [comment]
I think you need to install CUDA 8.0 instead ho 9.0 because there are some tensorflow libraries that are not compatible with CUDA 9.0

**Comment by longmalongma** [comment]
yes,I try to compile it ,a problem occurs.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tensorflow'
tf_conv3p_grid.cpp:1:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
compilation terminated.
nvcc fatal   : argument expected after '-I'
register_op.cpp:1:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
compilation terminated.
g++: error: register_op.o: No such file or directory
g++: error: tf_conv3p.so_cuda.o: No such file or directory
g++: error: tf_conv3p.so_cpu.o: No such file or directory
rm: cannot remove 'tf_conv3p.so_cpu.o': No such file or directory
rm: cannot remove 'tf_conv3p.so_cuda.o': No such file or directory





------------------ 原始邮件 ------------------
发件人: "saira05"<notifications@github.com>; 
发送时间: 2019年6月19日(星期三) 下午3:39
收件人: "saira05/DPRNet"<DPRNet@noreply.github.com>; 
抄送: "longma"<1442342449@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [saira05/DPRNet] Why can't compile? (#1)




Are you compiling this file?
 tf_conv3p_compile_tf14.sh

**Comment by longmalongma** [comment]
Think your reply,I can not install cuda8.0,because my all works on cuda9.0.




------------------ 原始邮件 ------------------
发件人: "saira05"<notifications@github.com>; 
发送时间: 2019年6月19日(星期三) 下午3:40
收件人: "saira05/DPRNet"<DPRNet@noreply.github.com>; 
抄送: "longma"<1442342449@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [saira05/DPRNet] Why can't compile? (#1)




I think you need to install CUDA 8.0 instead ho 9.0 because there are some tensorflow libraries that are not compatible with CUDA 9.0

**Comment by cuge1995** [comment]
> Think your reply,I can not install cuda8.0,because my all works on cuda9.0.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "saira05"<notifications@github.com>; 发送时间: 2019年6月19日(星期三) 下午3:40 收件人: "saira05/DPRNet"<DPRNet@noreply.github.com>; 抄送: "longma"<1442342449@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [saira05/DPRNet] Why can't compile? (#1) I think you need to install CUDA 8.0 instead ho 9.0 because there are some tensorflow libraries that are not compatible with CUDA 9.0 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

did you solve it ? I have the same problem
